[build]
  publish = "deploy"
  command = "echo 'No build command needed'"

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/src/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/src/css/*.css"
  [headers.values]
    Content-Type = "text/css"

# Redirect old paths to root
[[redirects]]
  from = "/public/*"
  to = "/:splat"
  status = 301