plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "deploy"
publishOrigin = "ui"
base = ""

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]